"""empty message

Revision ID: c7c38ef77e2c
Revises: 
Create Date: 2022-05-31 20:56:26.553030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c38ef77e2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('xml_ref_main', sa.String(), nullable=False),
    sa.Column('xml_objective', sa.String(length=500), nullable=True),
    sa.Column('objective_no', sa.String(), nullable=True),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('job', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=500), nullable=True),
    sa.Column('sub_ref_number', sa.String(), nullable=True),
    sa.Column('can_do_skill', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.String(length=500), nullable=True),
    sa.Column('grammar', sa.String(length=500), nullable=True),
    sa.Column('sub_obj_no', sa.String(), nullable=True),
    sa.Column('congruence', sa.String(), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('script_text', sa.String(length=1000), nullable=True),
    sa.Column('rubric_part_1', sa.String(length=500), nullable=True),
    sa.Column('rubric_part_2', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('xml_ref_main')
    ),
    op.create_table('questions',
    sa.Column('xml_ref_main', sa.String(), nullable=False),
    sa.Column('xml_ref_sub', sa.String(), nullable=False),
    sa.Column('item_number', sa.String(), nullable=True),
    sa.Column('final_rubric', sa.String(length=1000), nullable=True),
    sa.Column('question_number', sa.String(), nullable=True),
    sa.Column('stem', sa.String(length=1000), nullable=True),
    sa.Column('A', sa.String(length=500), nullable=True),
    sa.Column('B', sa.String(length=500), nullable=True),
    sa.Column('C', sa.String(length=500), nullable=True),
    sa.Column('D', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.String(length=500), nullable=True),
    sa.Column('scoring', sa.String(length=500), nullable=True),
    sa.Column('rat_opt_a', sa.String(length=500), nullable=True),
    sa.Column('rat_opt_b', sa.String(length=500), nullable=True),
    sa.Column('rat_opt_c', sa.String(length=500), nullable=True),
    sa.Column('rat_opt_d', sa.String(length=500), nullable=True),
    sa.Column('xml_ref_main', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('xml_ref_main')
    )
    op.create_table('section',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_table('job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_type',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('questions')
    op.drop_table('section')
    op.drop_table('job')
    op.drop_table('item_type')
    # ### end Alembic commands ###
